### ISSUE TITLE
Add chrome web store link where everyone would expect it.

### ISSUE THREAD

**Issue by RusseII** [Geczy/tinder-autopilot#3]
![image](https://user-images.githubusercontent.com/15036618/89781402-db953000-dad8-11ea-976b-618c640d797f.png)

Example:
![image](https://user-images.githubusercontent.com/15036618/89781430-ea7be280-dad8-11ea-9434-4cc526441864.png)

![image](https://user-images.githubusercontent.com/15036618/89781446-f23b8700-dad8-11ea-98a8-d31355cde378.png)

**Comment by Geczy** [comment]
Great idea, thanks!
